In [2]:
import numpy as np

In [5]:
np.version.version

'1.26.4'

### **LOOPS**

In [6]:
from numpy import array

In [10]:
array1=array([[1,2,3,4],[5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
for i in array1:
  print(i)

1
2
3
4


In [23]:
for i in array1:
  for j in i:
    print(j,end=" ")
    print()

1 
2 
3 
4 
5 
6 
7 
8 


In [24]:
for i in array1:
  for j in i:
    if(j%3==0):
      print(j)

3
6


In [30]:
#[1,2,3,4,5,6,7,8,9]
#([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

array([1,2,3,4,5,6,7,8,9]).reshape(3,3)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a=([1,2,3,4,5,6,7,8,9])
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
arr3=([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
np.hstack(arr3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
l=[]
for i in arr3:
  for j in i:
    l.append(j)
print(array(l))

[1 2 3 4 5 6 7 8 9]
